apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtun
  template:
    metadata:
      name: mtun
      labels:
        app: mtun
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: mtun
        image: ir0cn/mtun:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - "/usr/bin/mtun"
        - "server"
        - "-t"
        - "JMvKIpGEMgqUOkdQp3uQgb0bIW9SSzTF"
        volumeMounts:
        - name: tunnel
          mountPath: /dev/net/tun
          subPath: tun
      volumes:
      - name: tunnel
        hostPath:
          path: /dev/net/tun